Derive Canon for `StealthAddress`
dusk-network/dusk-pki pull request #17
Opened 2020-11-03 10:28 UTC by CPerezz

We need to have `Canon` derived for `StealthAddress` so that we can have structures that contain `StealthAddress`'s inside of themseleves and `Canon` can be derived for them.

Merge once https://github.com/dusk-network/Poseidon252/pull/88 has been merged and a new version has been released.

2020-11-03 11:57 UTC, ZER0 requested changes
Update the CI in order to be consistent with our other repos. As discussed you might want to put `Canon` behind a feature flag.

2020-11-03 21:44 UTC, CPerezz commented
> Update the CI in order to be consistent with our other repos. As discussed you might want to put `Canon` behind a feature flag.

Both done. Tell me what you think.

2020-11-04 10:18 UTC, ZER0 approved these changes

2020-11-04 10:18 UTC, ZER0 commented on Cargo.toml
> +canon = ["canonical", "canonical_derive", "dusk-jubjub/canon", "poseidon252/canon"]
Nit: add a new line

2020-11-04 11:11 UTC, merged